name: Test

on:
  push:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref_name }}
      - name: Make openwrt directory
        run: git clone https://github.com/coolsnowwolf/lede.git openwrt
      - name: cache
        uses: w311angg/cachewrtbuild@main
        with:
          ccache: true
          prefix: ${{ github.workspace }}/openwrt
          branch: ${{ github.ref_name }}
